- name: setup ALB
  elb_application_lb:
    name: devlb
    region: us-east-2
    security_groups:
      - sg-0af22d4c57c7bc446
    subnets:
      - subnet-245ef0688
      - subnet-496b2d33
      - subnet-88676fe0
    listeners:
      - Protocol: HTTP
        Port: 80
        DefaultActions:
          - Type: forward # Required. Only 'forward' is accepted at this time
            TargetGroupName: a1

- name: Add each EC2 instance to the ELB
      ec2_elb:
        state: present
        ec2_elbs: "{{ application }}-load-balancer"
        region: "{{ region }}"
        instance_id: "{{ item.id }}"
      with_items: "{{ ec2_instances.tagged_instances }}"
